				<div class="row">
					<div class="col-sm-12">
						<div class="col-content" id="privacy-legal">
							<h1>Legal</h1>

							<h2>PLEASE READ THIS AGREEMENT CAREFULLY BEFORE USING THIS SITE</h2>

							<h3>1. ACCEPTANCE OF TERMS</h3>
							<p>Enriched Academy (" Enriched ") is the owner of enrichedstart.com, dragonbank.com and enrichedacademy.com<br>
							(the " Sites "). The Terms of Use Agreement (the " Agreement ") governs your use of the Site including, without limitation, all content such as text, information, images, software and materials ( the " Content ") and the Services made available to you or by you through this Site by Enriched and/or third parties at any time. The Sites are designed to comply with Canadian laws and regulations. You can review the most current version of the Agreement at any timeby visiting our websites. By using the Site, you: (i) agree to be bound by the Agreement; (ii) represent and warrant that you are either: (a) at least eighteen (18) years old; or (b) a parent or legal guardian of a user that is under the age of eighteen (18) years old and legally responsible for such minor user's use of the Site; and (iii) represent and warrant that you have the legal authority to accept the Agreement. If you do not agree with the Agreement, you are not authorized to use the Site.</p>

							<h3>2. ACCESS TO THE SITE</h3>
							<p>Access to certain portions of this Site requires login and password information provided only to users who have registered (the " Registered Users "). The Site login and password are provided for the use of the individual Registered User only and are not transferable. Any user who obtains a login and password ( " ID ") by any means other than that user's own registration as a Registered User, is not authorized to use that ID and Enriched requests that such user notify Enriched of the improperly disclosed ID. Misuse of an ID, including, without limitation, unauthorized sharing of the ID may result, at Enriched's sole discretion, in cancellation of the Registered User's subscription and other remedies, and Enriched shall have no liability to the Registered User. Certain other Content or Services on the Sites may require additional identification or passwords. Registered Users are solely responsible for (1) maintaining the strict confidentiality of their IDs; (2) not allowing another person to use their IDs to access the Sites, (3) any damages or losses that may be incurred or suffered as a result of their failure to maintain the strict confidentiality of their IDs, and (4) promptly informing Enriched in writing of any need to deactivate an ID due to potential or actual security concerns. Enriched is not liable for any harm related to the theft of your ID, your disclosure of your ID, or your authorization to allow another person or entity to use your ID. You agree to immediately notify Enriched in writing of any unauthorized use of your ID.</p>

							<h3>3. CONTENT AND SERVICES</h3>
							<p>The Sites may provide certain Content and Services that Enriched may change or update from time to time, including, without limitation, providing children with an opportunity to track amounts they have earned, places to spend the money and/or charities or other not-for-profit organizations to which children can donate the money (the " Services "). The Site is designed to be used in conjunction with a parent or legal guardian (" Parent "). In all cases, the Parent shall have ultimate control over funds expended through or in connection with the Site. Enriched is not a bank.</p>
							<p>The ability to post Content may be provided to allow users and/or Registered Users to share ideas and information of interest. Enriched cannot and does not monitor all of the Content posted or transmitted by users and Registered Users. Users and Registered Users are advised to use their best judgment when choosing to participate in any information sharing activity. Any disclosures made throughor from the Sites should only be made after reviewing and agreeing to the Privacy Policy found one our Sites . In the event that any posted Content appears to be inappropriate for display on the Sites for any reason, users and Registered Users are encouraged to contact Enriched to request removal of such Content.</p>

							<h3>4. DISCLAIMERS</h3>
							<p>NEITHER ENRICHED NOR THE SITES (INCLUDING, WITHOUT LIMITATION, THE CONTENT AND THE SERVICES) PROVIDES LEGAL, TAX OR FINANCIAL ADVICE. Enriched IS NOT A FINANCIAL PLANNER, BROKER, TAX ADVISOR OR A BANK. The Site is a money management website intended to assist you and your children in becoming financially responsible and socially aware. For some Services, you may direct Enriched to retrieve or store certain Account Information (as defined in the Privacy Policy). Enriched reserves the right, but does not have the obligation, to review the Account Information for any purposes, including, without limitation, for accuracy or legality. The accuracy of the Services depends on the accuracy of the information you submit. Your financial situation is unique and the Content and Services may not be appropriate for your situation and you are advised to seek professional advice before relying on any Content or Services found on the Site.</p>

							<h3>5. INTELLECTUAL PROPERTY RIGHTS</h3>
							<p>(a) Copyright<br>
								All intellectual property rights in the Content (including copyrights, trademarks, trade secrets and patents) are the property of Enriched unless indicated otherwise and are protectedunder copyright laws and other applicable intellectual property laws. Certain materials are used by permission of their respective owners. The Content is provided solely to enable users to obtain information on topics of interest. The Content may not be copied, reproduced, republished, uploaded, posted, transmitted, or distributed in any way without the prior written permission of Enriched, except that, subject to your compliance with this Agreement, Enriched authorizes you to view or download a single copy of the Content for your personal, non-commercial use, provided that you keep intact all copyright, trademark, and other proprietary notices. Modification or use of Content for any other purpose is a violation of the rights of Enriched or third parties.</p>
							<p>(b) Copyright Modernization Act<br>
								Pursuant to the Copyright Modernization Act), Enriched's designated agent for questions related to copyright with the Sites is:<br>
								Site Administrator<br>
								<a href="mailto:support@enrichedacademy.com">support@enrichedacademy.com</a></p>
							<p>(c) Data<br>
								From time to time, you may provide Enriched with information, including, without limitation, Account Information (as defined in the Privacy Policy), Personal Information (as defined in the Privacy Policy), suggestions, ideas and/or any other content ( " Data "). You hereby grant to Enriched a non-exclusive license to the Data solely for providing the Content and Services, for operating the Site and for other purposes permitted by or set forth herein. You represent and warrant that you have obtained all necessary rights to provide the Data to Enriched for use for these purposes.</p>

							<h3>6. USE OF THE SITE AND REGISTRATION REQUIREMENTS</h3>
							<p>Use of the Site is voluntary. You may choose not to use the Site and you may choose not to use your ID. You may cancel your ID at any time by contacting Enriched at the addresses provided below. If you choose to have an ID, you agree that you will be responsible for maintaining your ID as confidential and for any activity that occurs as a result of your enabling or permitting another person or entity to use your ID. You agree to immediately notify Enriched by one of the methods below in the event that (i) your ID is lost or stolen, or (ii) you become aware of any unauthorized use of your ID or of any other breach of security related to the Site. Enriched is not responsible for any loss or damage arising from your failure to comply with the provisions of this section.</p>

							<p>You may contact Enriched as follows:<br>
								Enriched Academy.<br>
								<a href="mailto:support@enrichedacademy.com">support@enrichedacademy.com</a></p>

							<p>Some of your Account Information may be stored by third parties, such as your bank or other third party payment processors. You hereby authorize Enriched to access your Account Information that is maintained by identified third parties on your behalf as your agent to fulfill your participation in the Site. Enriched will, as applicable, submit information that you provide to Enriched to the applicable third party. You hereby authorize and permit Enriched to use information submitted by you to the Services (if any) to accomplish the foregoing and to configure the Services so that it is compatible with the third party sites for which you submit your information. Solely to fulfill the Services hereunder, you grant Enriched a limited power of attorney and appoint Enriched as your attorney-in-fact and agent to access third party sites, retrieve and use your information with the full power and authority to do and perform each thing necessary in connection with such activities. YOU ACKNOWLEDGE AND AGREE THAT WHEN ENRICHED IS ACCESSING AND RETRIEVING YOUR ACCOUNT INFORMATION FROM THIRD PARTY SITES, ENRICHED IS ACTING SOLELY AS YOUR AGENT AND YOU SHALL BE ULTIMATELY RESPONSIBLE FOR ENRICHED’S USE OF SUCH INFORMATION.</p>

							<h3>7. PROHIBITED BEHAVIOR</h3>
							<p style="margin-bottom: 10px;">You are responsible for all Content that you upload, post, email or otherwise transmit using the Sites. Likewise, you are responsible for respecting Enriched and third parties' rights with respect to Content that appears on the Sites and not to download, email or otherwise transmit such Content in violation of Enriched's and third parties' rights. You shall not use the Site or Services to:</p>
							<ul>
								<li>Upload, post, email, or otherwise transmit any Content that infringes any patent, trademark, trade secret, copyright or other intellectual property right, privacy right, or publicity right of any person or entity. By uploading, posting, emailing or otherwise transmitting any Content, you represent and warrant that you have all rights to take such action with respect to the Content;</li>
								<li>Upload, post, email, or otherwise transmit any Content that is illegal, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, pornographic, sexually explicit, invasive of another's privacy, hateful or racially, ethnically, or otherwise offensive;</li>
								<li>Impersonate another person or entity, including without limitation, a representative of Enriched or its officers, directors, employees, contractors or agents, falsely represent or misrepresent your affiliation with another person or entity, or forge headers or otherwise manipulate identifiers that would disguise the origin of any Content transmitted to or through the Site;</li>
								<li>Upload, post, email or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, including without limitation, initiation or perpetuation of any "Spam", "Junk Mail", chain letters, or any other potentially objectionable form of unsolicited communication;</li>
								<li>Collect or store personal data with respect to third parties except as contemplated by the Agreement;</li>
								<li>Directly or indirectly, intentionally disrupt or interfere with the Site in any manner that may materially adversely affect Enriched or any third party;</li>
								<li>Upload, post, email or otherwise transmit any material that contains software viruses or any other code, files or programs designed or known to disable, interrupt, or limit the functionality of any computer hardware, computer software, or telecommunications equipment or facilities; or,</li>
								<li>Upload, post, email or otherwise transmit without authorization any material that contains personal or private information concerning any third party person or entity, including without limitation, phone number(s) or addresses, credit/debit cards, calling cards, account numbers, social security numbers, passwords or other similar information.</li>
							</ul>

							<h3>8. DISCLAIMER OF WARRANTIES</h3>
							<p>THE USE OF THE SITE IS SOLELY AT YOUR OWN RISK. THE SITE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. ENRICHED EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND WITH RESPECT TO THE SITE (INCLUDING, WITHOUT LIMITATION, THE CONTENT AND/OR SERVICES OFFERED ON THE SITE) WHETHER EXPRESSED OR IMPLIED INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. ENRICHED EXPRESSLY DISCLAIMS ANY RESPONSIBILITY FOR THE ACTIONS OF ANY REGISTERED USER OR OTHER USER WHO USES THE SITE. IF A JURISDICTION, PROVINCE OR STATE DOES NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. ENRICHED MAKES NO WARRANTY THAT THE SITES WILL MEET YOUR REQUIREMENTS, OR WILL BE UNINTERRUPTED, TIMELY, SECURE, CURRENT, ACCURATE, COMPLETE, OR ERROR-FREE OR THAT THE RESULTS THAT MAY BE OBTAINED BY USE OF THE SITES WILL BE ACCURATE OR RELIABLE. YOU UNDERSTAND AND ACKNOWLEDGE THAT YOUR SOLE AND EXCLUSIVE REMEDY WITH RESPECT TO ANY DEFECT IN OR DISSATISFACTION WITH THE SITES IS TO CEASE TO USE THE SITE. YOU MAY HAVE OTHER RIGHTS WHICH MAY VARY FROM PROVINCE-TO-PROVINCE OR STATE-TO-STATE OR WITHIN NATIONAL JURISDICTIONS.</p>

							<h3>9. EXCLUSIONS AND LIMITATION OF LIABILITY</h3>
							<p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT ENRICHED SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA LOSS, OR OTHER LOSSES (EVEN IF ENRICHED HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES) RESULTING FROM ANY MATTER RELATED TO YOUR USE OF THE SITE.</p>

							<h3>10. LINKS TO OTHER SITES</h3>
							<p>The linked sites are not under the control of Enriched and Enriched is not responsible for nor does it certify the content of any linked site or any link contained in a non-affiliated linked site. Enriched reserves the right to terminate any link or linking program at any time. Enriched may have selected the links for your convenience. The selection or omission of links is not intended to endorse any particular companies or products. If you decide to access any of the third party sites linked to the Sites, you do this entirely at your own risk. ENRICHED DOES NOT ACT AS AN AGENT OF ANY THIRD PARTY, EXCEPT TO THE EXTENT SET FORTH IN SECTION 6.</p>

							<h3>11. APPLICABLE LAWS</h3>
							<p>The Sites are controlled by Enriched from its location in Canada. Those who choose to access the Sites from other locations do so on their own initiative and are responsible for compliance with applicable local laws. You may not use or export the Content or Services in violation of Canadian export laws or regulations. Any claim relating to the Sites must be filed within one year after such claim or cause of action arose and shall be governed by the internal substantive laws of the Province of Ontario without regard to its conflicts of laws provisions. Venue with respect to any dispute between the users and Enriched will rest exclusively in the Province or federal courts located in Ontario, Canada.</p>

							<h3>12. ENTIRE AGREEMENT</h3>
							<p>This Agreement, including the Privacy Policy, and any other Enriched policy which is incorporated herein by this reference, contains the entire agreement between you and Enriched relating to the subject matter hereof, and supersedes any other oral or written communications relating thereto. Enriched reserves the right to make changes to this Agreement at any time without advance notice. Enriched shall post all amended forms of this Agreement on the Sites and such amended forms shall be effective immediately upon its posting. It is at all times your responsibility to read the most current form of this Agreement before using the Sits to ensure that you agree to the terms and conditions of any amendments made to this Agreement. You agree that these standards for notice of amendments to this Agreement are reasonable.</p>

							<h3>13. TERMINATION</h3>
							<p>Your right to access and use the Sites, Services and/or Content immediately terminates without further notice upon your breach of this Agreement. Enriched may terminate this Agreement and/or your right to use the Sites at any time, with or without cause. Enriched reserves the right to discontinue or make changes to the Sites, Content and/or Services at any time.</p>

							<h3>14. NOTICE</h3>
							<p>Enriched may deliver notice to you under this Agreement by means of electronic mail, a general notice on Enrichedacademy.com , or any of the Enriched Sites by written communication delivered by mail to your address on record in Enriched' account information. You may give notice to Enriched at any time via electronic mail to <a href="mailto:support@Enrichedacademy.com">support@Enrichedacademy.com</a> If you object to any material found on this Site, please bring your concerns to the attention of <a href="mailto:support@enrichedacademy.com">support@Enrichedacademy.com</a>. The Site administrator reserves the right to remove any material pending further investigation.</p>

							<h3>15. GENERAL</h3>
							<p>You agree to be bound by this Agreement and any modifications to this Agreement occurring prior to your continued use of the Content, Services or access to the Site. You should visit this Agreement from time to time to review the current terms of this Agreement because they shall be equally binding on you. Certain provisions of this Agreement may be superseded by expressly designated legal notices or terms located on particular pages at this Sites. The headings of articles and sections contained in this Agreement are for reference purposes only and shall not affect in any way the meaning or interpretation of this Agreement. If any provision of this Agreement is found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions. A waiver of a breach of any provision to this Agreement will not constitute a waiver of any other breach. Enriched reserves the right to add to or change the Sites or cease offering the Sites (or any Content or Services on the Sites) at any time and without liability. Enriched reserves the right to refuse to offer access to the Sites to anyone at anytime without notice. You may not assign this Agreement without Enriched' prior written permission. This Agreement is binding upon your successors, assigns, heirs and executors.</p>

							<p>YOUR USE OF THE SITES INDICATES THAT YOU AGREE TO THE FOREGOING AGREEMENT. IF YOU DO NOT AGREE TO THE AGREEMENT, DO NOT USE THE SITES.</p>


						</div>
					</div>
				</div>
